openapi: 3.0.3

info:
  title: KELA - Investigate API
  version: "1.0"
  license: 
    name: KELA
    url: https://docs.ke-la.com/kela-docs/
  description: |
    The Investigate module RESTful API is designed to allow quick, flexible and easy searches against KELA‚Äôs data lakes in real time. It‚Äôs comprised of several GET and POST endpoints allowing for different operations, all returning JSON output.

servers:
  - url: https://platform.ke-la.com/api/investigate/v1
    description: Production environment

security:
  - ApiKeyAuth: []

tags:

  - name: "Connectivity"
    description: |
      The Investigate module API interface is accessible via the following address:
      ```http
      https://platform.ke-la.com/api/investigate/v1
      ```

  - name: "Considerations"
    description: |
      To ensure optimal performance, please adhere to the following technical limits:

      | Feature | Specification |
      | :--- | :--- |
      | **Rate Limit** | 1 request per second |
      | **Max Query Length** | 2000 characters |
      | **Auth Method** | `apiToken` (Query Parameter) |

  - name: "Before You Start"
    description: |
      An API Token is required in order to use the Queries API.
      The API token can be generated through the KELA platform UI, within the system menu.
      <p align="center">
        <img src="https://docs.ke-la.com/api-documentation/~gitbook/image?url=https%3A%2F%2F859333317-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FO5SB0YyAgvzG9M9dPZV7%252Fuploads%252FTJQdvVEtCgNG3eiheNUo%252Fimage.png%3Falt%3Dmedia%26token%3D4ced3c4f-6096-4223-b7c1-1105225774cd&width=768&dpr=4&quality=100&sign=4f15921b&sv=2" >
      </p>

  - name: "Authentication"
    description: |
      After acquiring this token, it should be used as a **URL parameter** ‚Äì appending `apiToken=...` to each API request.

      > ‚ö†Ô∏è **Important:** Ensure the token is included in every request to avoid `401 Unauthorized` errors.

  - name: "Query Logic"
    description: |
      Note that each query type (e.g., Free Text, Domain, etc.) has been designed to provide the best possible match to the search term. 
      
      * **Default behavior:** The search engine uses **‚ÄúFree text‚Äù** as the default query type.

      An Investigate query, which can be sent to the [Data Counters](#operation/counters) or [Data Search](#operation/search) endpoints, is comprised of three parameters:

      **1. The Query:** The actual text strings to search. It can include Boolean logic, search operators, and metadata field searches.

      | Query | Query Type | Meaning |
      | :--- | :--- | :--- |
      | `‚Äúcve-2019-0708‚Äù` | Free Text | Search for all data containing the string exactly |
      | `‚ÄúSharon Opportunities‚Äù AND (scampage OR phishing)` | Free Text | Search for data containing the first string AND one of the others |
      | `author.name: GandCrab` | Free Text | Search for data written by users with the handle GandCrab |
      | `sharonopportunities.com` | Domain | Search for the domain name or its subdomains |
      | `sharon@sharon-opp.com` | Email | Search for the exact email address |
      | `23.0.0.1/24` | Subnet | Search for an IPv4 address within the CIDR range |
      | `‚Äú23.0.0.1/24‚Äù` | Free Text | Search for the exact string "23.0.0.1/24" |
      | `458021` | Credit Card | Search for credit cards issued with the 458021 BIN |

      **2. The Query Type / Descriptor:** If searching for a structured entity (domain, subnet, etc.), setting the correct type ensures more accurate results.

      **3. Data Type:** Specifies the data lake in which to search.

      | Data Type | Details |
      | :--- | :--- |
      | **Hacking Discussions** | Raw data from hacking forums, illicit markets, and Dark Net communities |
      | **Leaked Credentials** | Third-party breaches and compromised databases |
      | **Compromised Accounts** | Data from machines infected by banking botnets |
      | **Instant Messaging** | Raw data from Telegram and Discord |
      | **Breached Servers** | Data from Remote Access Markets (cracked/breached servers) |
      | **Finished Intelligence** | Reports and insights from KELA's Threat Research team |

      > üí° **Notice:** For full specification and examples of query types, please refer to the *Investigate Searches* chapter in the module user guide.
  - name: Query API
    description: |
      Performing a query is done via simple GET and POST requests, made to one of four endpoints:

      [**Data Counters:**](#operation/counters) submit a general query against KELA‚Äôs data lake and receive an object specifying how many hits exist for each data type supported by the Investigate module (i.e. hacking discussions, leaked credentials, etc.).
      
      [**Data Search:**](#operation/search) submit a query against a pre-defined data type and receive a list of hits against your query. For some data types, the list will include all the details needed; others may require querying specific query IDs against the **Get Data** endpoint. This endpoint returns different types of objects based on the data type queried. 
      > **Notice:** querying this endpoint costs **1 search token**.
      
      [**Search Pagination:**](#operation/next) dedicated pagination endpoint, allowing you to continuously paginate through a data set obtained by the "Data Search" endpoint. 
      > **Notice:** for every 100 pagination requests, a search token will be consumed from your account.
      
      [**Get Data:**](#operation/getdata) submit an ID of a specific data point returned by the "Data Search" endpoint to get the full content of the data. This endpoint is only required for data types that may contain big texts or attached files and thus can‚Äôt be pulled in bulk via the "Data Search" endpoint.
      
      ---
      **Workflow Overview**
      Following is a general diagram showing how the three prominent endpoints can be used as part of a complete workflow. However, each endpoint can be queried independently ‚Äì there‚Äôs no necessity to go by the flow depicted below.
      <p align="center">
        <img src="https://docs.ke-la.com/api-documentation/~gitbook/image?url=https%3A%2F%2F859333317-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FO5SB0YyAgvzG9M9dPZV7%252Fuploads%252FvdKdsNgiqtlUeprLeEjo%252FAPI%2520workflow.png%3Falt%3Dmedia%26token%3Dba13d11b-ad99-49f6-866b-fb1de749233f&width=768&dpr=1&quality=100&sign=38ae0de&sv=2" >
      </p>
  - name: Saved Queries API
    description: |
      ### **Overview**

      Saved Queries are instances that allow you to both revisit saved searches whenever relevant, as well as get email notifications for new results. 

      > Notice: for more details please refer to the Saved Queries page in the Investigate module user guide.

      Investigate‚Äôs API allows you to fetch information about your in-use saved queries, as well as the data from a specific saved query (either all results or new ones since your last visit).
  - name: User License API
    description: |
      The **"User License"** API features a single endpoint that allows you to fetch your license details. 

      This operation may be useful in order to regulate searches ‚Äì for example, decide whether or not to carry out multiple pagination requests that will consume many search tokens if your current token allotment is low.

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: apiToken
      description: "Enter your KELA API Token here."
  schemas:
    DataSearchResponse:
      type: object
      properties:
        data:
          type: object
          properties: 
            results:
              type: array
              items: 
                oneOf: 
                  - $ref: "#/components/schemas/ResultDS-HD"
                  - $ref: "#/components/schemas/ResultDS-LC"
                  - $ref: "#/components/schemas/ResultDS-IM"
                  - $ref: "#/components/schemas/ResultDS-CA"
                  - $ref: "#/components/schemas/ResultDS-BS"
                  - $ref: "#/components/schemas/ResultDS-IR"
            total:
              type: object
              properties: 
                value:
                  type: integer
                  description: Amount of results.
                relation:
                  type: string
                  description: "Type of results"
            filters:
              type: object
              properties:
                authors:
                  type: array
                  items: 
                    type: object
                    properties: 
                      key:
                        type: string
                      doc_count:
                        type: integer
                crawlers:
                  type: array
                  items: 
                    type: object
                    properties: 
                      key:
                        type: string
                      crawler_count:
                        type: integer
                      doc_count:
                        type: integer
                crawlerTypes:
                  type: array
                  items: 
                    type: object
                    properties: 
                      key:
                        type: string
                      crawler_count:
                        type: integer
                      doc_count:
                        type: integer
                geographies:
                  type: array
                  items: 
                    type: object
                    properties: 
                      key:
                        type: string
                      crawler_count:
                        type: integer
                      doc_count:
                        type: integer
            scroll_id:
              type: string
              description: "ID"
    ResultDS-HD:
      type: object
      properties:
        crawler:
          type: string
          example: Pastebin
        author:
          type: object
          properties:
            uid:
              type: string
              nullable: true
            name:
              type: string
            url:
              type: string
              format: uri
        media:
          type: object
          description: Informaci√≥n de medios asociados (puede estar vac√≠o)
        id:
          type: string
        title:
          type: string
        url:
          type: string
          format: uri
        posted_date:
          type: integer
          description: Timestamp UNIX
        text:
          type: string
        index:
          type: string
        mediaCount:
          type: integer
        mediaArray:
          type: array
          description: ""
    ResultDS-LC:
      type: object
      properties:
        email:
          type: string
        domain:
          type: string
        passwordType:
          type: string
        password:
          type: string
        sourceType:
          type: string
        source:
          type: string
        source_id:
          type: string
        postedDate:
          type: string
        service:
          type: string
        userName:
          type: string
        serviceRaw:
          type: string
        sourceTypeRaw:
          type: string
    ResultDS-IM:
      type: object
      properties:
        is_event:
          type: boolean
        posted_date:
          type: integer
          description: Timestamp UNIX
        user_name:
          type: string
        id:
          type: string
        crawler:
          type: string
          example: CardingStyleTG
        type:
          type: string
          example: chatTypeSupergroup
        chat_id:
          type: integer
          format: int64
        full_name:
          type: string
        source:
          type: string
        message_id:
          type: integer
          format: int64
        user_id:
          type: string
        author_uid:
          type: string
        index:
          type: string
          example: instant_messaging
        title:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/TelegramMessage'
    TelegramMessage:
      type: object
      properties:
        text:
          type: string

        user_name:
          type: string

        order:
          type: integer

        posted_date:
          type: integer

        hasFile:
          type: boolean
          nullable: true

        hasText:
          type: boolean
          nullable: true

        highlight_image:
          type: boolean
          nullable: true
    ResultDS-CA:
      type: object
      properties:
        bot_guid:
          type: string
          description: Identificador √∫nico del bot
        id:
          type: string
        service:
          type: string
          format: uri
        update_date:
          type: integer
          description: Timestamp UNIX de √∫ltima actualizaci√≥n
        source:
          type: string
          example: Agressor
        source_type:
          type: string
          example: indexer.bot_markets
        source_type_description:
          type: string
          example: Bot Markets
        bot_installation_date:
          type: integer
          nullable: true
          description: Timestamp UNIX de instalaci√≥n del bot
        module:
          type: string
          example: Smoke
        userName:
          type: string
        password:
          type: string
          description: Credencial obtenida por el bot
    ResultDS-BS:
      type: object
      properties:
        access_type:
          type: string
          example: CMS Admin Access
        index:
          type: string
          example: breached_servers
        title:
          type: string
          example: fifocolombia.com.co
        subTitle:
          type: string
          example: " ¬∑ CMS Admin Access"
        seller:
          type: string
        price:
          type: number
          example: 5
        id:
          type: string
        text:
          type: string
          description: Descripci√≥n completa del acceso ofrecido
        cms:
          type: string
          example: Wordpress
        technology:
          type: string
          example: Unknown
        tool:
          type: string
        website_title:
          type: string
        first_checked:
          type: integer
          nullable: true
          description: Timestamp UNIX del primer chequeo
    ResultDS-IR:
      type: object
      properties:
        summary:
          type: string
          description: Resumen ejecutivo del informe
        is_highlight:
          type: boolean
        data_file:
          $ref: '#/components/schemas/ReportFile'
        iocs:
          type: array
          items: {}
        image_files:
          type: array
          items: {}
        published:
          type: boolean
        title:
          type: string
        type:
          type: string
          example: intelligence_reports
        threat_actor_names:
          type: array
          items:
            type: string
        external_sources:
          type: array
          items:
            type: string
        is_deleted:
          type: boolean
        associated_threat_actors:
          type: array
          items:
            type: string
        tlp:
          type: integer
          description: Traffic Light Protocol level
        threat_actor_type:
          type: array
          items:
            type: string
        mitre:
          type: array
          items:
            type: string
        id:
          type: string
        sector:
          type: string
          nullable: true
        posted_date:
          type: integer
          description: Timestamp UNIX de publicaci√≥n
        indexed_date:
          type: integer
          description: Timestamp UNIX de indexaci√≥n
        document_type:
          type: string
          example: report
        references:
          type: array
          items:
            type: string
        isDeleted:
          type: boolean
        authorized:
          type: boolean
        reportType:
          type: string
          example: Emerging Threats
        text:
          type: string
        index:
          type: string
          example: intelligence_reports
        pdf:
          type: string
          format: uri
    ReportFile:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          example: pdf
        key:
          type: string
          description: Ruta interna del archivo







paths:

  /counters:
    post:
      operationId: counters
      tags: [Query API]
      summary: Data Counters
      description: |
        The **"Data Counters"** endpoint returns a list of the data types that in which hits for the executed query were found, with the amount of hits per data type. It does not return the actual data, and as such its output may be used in order to build queries for the **"Data Search"** endpoint.
        <div style="background-color: #f9f9f9; border: 1px solid #e5e5e5; padding: 12px; border-radius: 4px; font-family: 'Source Code Pro', monospace; font-size: 0.9em; margin: 15px 0;">
          <span style="color: #248fb2; font-weight: bold; margin-right: 10px;">POST</span> 
          <a href="https://platform.ke-la.com/api/investigate/v1/counters" style="color: #333; text-decoration: none; border-bottom: 1px dotted #248fb2;">https://platform.ke-la.com/api/investigate/v1/counters</a>
        </div>
      parameters:
        - name: query
          in: query
          required: true
          schema: { type: string }
          example: ke-la.com
        - name: entity
          in: query
          required: true
          description: | 
              \
              Define the entity type to optimize search accuracy.
          schema:
            type: string
            default: "text"
            enum: 
              - text
              - domains
              - emails
              - subnets
              - credit_cards
      requestBody:
        required: false 
        content: 
          application/json:
            schema: 
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    start_date:
                      type: string
                      format: date
                      description: Start date for the search range using DD/MM/YYYY format.
                    end_date:
                      type: string
                      format: date
                      description: End date for the search range using DD/MM/YYYY format.
            examples: 
              no_filters:
                summary: No filters
                value: {}
              date_filter:
                summary: Date range filter
                value:
                  filters:
                    start_date: "01/12/2020"
                    end_date: "30/12/2020"
        
      responses:
        "200":
          description: Counters per data type
          content:
            application/json:
              example:
                data:
                  - name: hacking_discussions
                    counter: 1058
                  - name: leaked_credentials
                    counter: 38853
                  - name: instant_messaging
                    counter: 1650
                  - name: compromised_accounts
                    counter: 526
                  - name: breached_servers
                    counter: 1250
                  - name: intelligence_reports
                    counter: 755
        "400":
          description: Bad Request
          content: 
            application/json:
              example:
                - message: entity must be one of ["text","subnets","emails","domains","credit_cards"]
        "401":
          description: Unauthorized
          content: 
            application/json:
              example:
                - message: You are not authorized.
        "429":
          description: Rate limit exceeded
          content: 
            application/json:
              example:
                - message: Too Many Requests.

  /search:
    post:
      operationId: search
      tags: [Query API]
      summary: Data Search
      description: |
        **Endpoint URL**

        <div style="background-color: #f9f9f9; border: 1px solid #e5e5e5; padding: 12px; border-radius: 4px; font-family: 'Source Code Pro', monospace; font-size: 0.9em; margin: 15px 0;">
          <span style="color: #248fb2; font-weight: bold; margin-right: 10px;">POST</span> 
          <a href="https://platform.ke-la.com/api/investigate/v1/search" style="color: #333; text-decoration: none; border-bottom: 1px dotted #248fb2;">https://platform.ke-la.com/api/investigate/v1/search</a>
        </div>

        This endpoint performs a full-text search across the selected index.

        ### Example request

        ```bash
        curl -X POST \
          "https://platform.ke-la.com/api/investigate/v1/search?apiToken=YOUR_API_TOKEN&query=test.com&entity=domains&index=compromised_accounts" \
          -H "Content-Type: application/json" \
          -d '{
            "filters": {
              "sources": ["Genesis"]
            }
          }'
      parameters:
        - name: query
          in: query
          required: true
          schema: { type: string }
          example: ke-la.com
        - name: entity
          in: query
          required: true
          schema:
            type: string
            enum: [text, domains, emails, subnets, credit_cards]
          example: domains
        - name: index
          in: query
          required: true
          schema:
            type: string
            enum:
              - hacking_discussions
              - leaked_credentials
              - instant_messaging
              - compromised_accounts
              - breached_servers
              - intelligence_reports
          example: compromised_accounts
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  description: Search filters
                  properties:
                    start_date:
                      type: string
                      description: Start date for the search range using DD/MM/YYYY format.
                      example: "01/12/2020"
                    end_date:
                      type: string
                      description: End date for the search range using DD/MM/YYYY format.
                      example: "30/12/2020"
                    sources:
                      type: array
                      description: Name of the KELA source from which you want to obtain results.
                      items:
                        type: string
                      example: ["Genesis"]
                    services:
                      type: array
                      description: URL or IP address of the affected service for which you want to obtain results
                      items:
                        type: string
                      example: ["verified.domain.com"]
                  additionalProperties: false
              
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/DataSearchResponse"
              examples:
                Hacking-Discussions-Response:
                  summary: Hacking Discussions Response
                  value: 
                    data:
                      results:
                        - crawler: Pastebin
                          author:
                            uid: null
                            name: josamex
                            url: https://pastebin.comu/josamex
                          media: {}
                          id: "368900410"
                          title: Untitled
                          url: https://pastebin.com/d7CFVnf2
                          posted_date: 1768354629
                          text: |
                            ...Duraci√≥n: 10 d√≠as

                            Inversi√≥n: Cotizaci√≥n personalizada

                            Objetivo:

                            Certificamos a TU instructor in-house...
                          index: hacking_discussions
                          mediaCount: 1
                          mediaArray: []
                      total:
                        value: 39086
                        relation: "eq"
                      filters:
                        authors:
                          - key: "bigv"
                            doc_count: 4684
                        crawlers:
                          - key: "Pastebin"
                            doc_count: 30440
                        crawlerTypes:
                          - key: "Forum"
                            crawler_count: 87
                            doc_count: 2626
                        geographies:
                          - key: "France"
                            crawler_count: 1
                            doc_count: 1
                      scroll_id: "556d1087f3c760a8c3a65625af4dc8457982ee56b97a3a4d7615b646d772af4c"
                Instant-Messaging-Response:
                  summary: Instant Messaging Response
                  value:
                    data:
                      results:
                        - is_event: false
                          posted_date: 1769106332
                          user_name: mitekk1
                          id: 7f7ae2b067cdc6057d668b47af71ec63
                          crawler: CardingStyleTG
                          type: chatTypeSupergroup
                          chat_id: -1001992347780
                          full_name: Mitek
                          source: Telegram V4
                          message_id: 372376600576
                          user_id: "8192012445"
                          author_uid: f70a516fd6dfc73d9143a1c638310f31
                          index: instant_messaging
                          title: ùìíùì™ùìªùì≠ùì≤ùì∑ùì∞ ùì¢ùìΩùîÇùìµùìÆ
                          messages:
                            - text: |
                                üí≤ TEMARIO ENERO 2026 üí≤
                                Duraci√≥n estimada: 1 a 2 semanas
                              user_name: the_carding_killer
                              order: 0
                              posted_date: 1769106261

                            - text: "...üí≤2Ô∏è‚É£5Ô∏è‚É£mxn"
                              user_name: mitekk1
                              order: 1
                              posted_date: 1769106332
                              hasFile: false
                              hasText: true
                              highlight_image: false

                            - text: TELEGRAM PREMIUM üåü
                              user_name: Ruso
                              order: 2
                              posted_date: 1769106334

        "400":
          description: Bad Request
          content: 
            application/json:
              example:
                - message: entity must be one of ["text","subnets","emails","domains","credit_cards"]
        "401":
          description: Unauthorized
          content: 
            application/json:
              example:
                - message: You are not authorized.
        "429":
          description: Rate limit exceeded
          content: 
            application/json:
              example:
                - message: Too Many Requests.

  /next:
    get:
      operationId: next
      tags: [Query API]
      summary: Search Pagination
      parameters:
        - name: scrollId
          in: query
          required: true
          schema: { type: string }
          example: abcdef123
      responses:
        "200":
          description: Pagination results
          content:
            application/json:
              example:
                data:
                  results: []
        "500":
          description: Fail to get next page

  /get/{type}/{id}:
    get:
      operationId: getdata
      tags: [Query API]
      summary: Get Data
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum:
              - hacking_discussions
              - instant_messaging
              - breached_servers
              - intelligence_reports
        - name: id
          in: path
          required: true
          schema: { type: string }
        - name: extract_entities
          in: query
          schema:
            type: boolean
          example: false
      responses:
        "200":
          description: Full data object
          content:
            application/json:
              example:
                data:
                  id: "123"
        "404":
          description: Not found

  /subscriptions:
    get:
      operationId: subscriptions
      tags: [Saved Queries API]
      summary: List Saved Queries
      responses:
        "200":
          description: List of saved queries
          content:
            application/json:
              example:
                - id: abc123
                  title: Test Query
                  search_text: test.com
                  new_results: 0

  /subscriptions/{id}:
    get:
      operationId: getsubscription
      tags: [Saved Queries API]
      summary: Get Saved Query Results
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
        - name: new
          in: query
          schema: { type: boolean }
          example: false
      responses:
        "200":
          description: Saved query results
          content:
            application/json:
              example:
                data:
                  results: []
                  scroll_id: abcdef

  /license:
    get:
      operationId: license
      tags: [User License API]
      summary: Get User License
      responses:
        "200":
          description: License details
          content:
            application/json:
              example:
                search_tokens_left: 120
                refill_date: 1700000000
                min_date_limit: 1600000000
